import type { Metadata } from 'next'
import { Header } from './header';

 const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

 function MyDoctorLayout({ children }:{
    children: React.ReactNode
  }) {
  return (
    <div>
      <Header />
      <div className="container">{children}</div>
    </div>
  );
}

export { MyDoctorLayout as default, metadata };